from setuptools import setup, find_packages

setup(
    name='yk-gentopia',
    version='0.0.1',
    packages=find_packages(exclude=['llm', 'llm.*']),
    url='https://github.com/yakami129/Gentopia',
    license='MIT license',
    author='billxbf',
    author_email='billxbf@gmail.com',
    description='Gentopia provides extensive utilities to assembles ALM agents driven by configs.',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    extras_require={
            'huggingface': ['torch', 'transformers', 'optimum', 'peft'],
        },
    install_requires=[
        'urllib3==1.26.16',
        'h11==0.12.0',
        'anyio==3.7.1',
        'huggingface-hub==0.16.4',
        'free-proxy',
        'lxml==4.7.1',
        'tenacity',
        'python-dotenv',
        'arxiv',
        'chardet',
        'cchardet',
        'numexpr',
        'googlesearch-python',
        'wolframalpha',
        'numpy',
        'rich',
        'tqdm',
        'prompt-toolkit',
        'regex',
        'attrs',
        'fastapi==0.99.1',
        'geopy',
        'pydantic==1.9',
        'pytest',
        'PyYAML',
        'requests',
        'setuptools',
        'uvicorn',
        'openai',
        'pexpect',
        'gradio_client',
        'pinecone-client',
        'chroma',
        'chromadb',
        'tiktoken',
        'scholarly'
    ],
)
